#### @baseURL = https://ejam-depl.herokuapp.com/
@baseURL = http://localhost:3200/
### Get
GET {{baseURL}}deployment

### add deployment
POST {{baseURL}}deployment
Content-Type: application/json

{
    "url": "https://www.npoint.io/asasadsds",
    "templateName": "Hidayt Testasas",
    "version": "1.0.3"
}


### delete deployment
DELETE  {{baseURL}}deployment
Content-Type: application/json

{
    "templateName": "Roy WIls"
}