@baseURL = http://localhost:3200/
### Get
GET {{baseURL}}deployment

### add deployment
POST {{baseURL}}deployment
Content-Type: application/json

{
    "URL": "https://www.npoint.io/docs/8f7cf8628b367ffd50a2",
    "templateName": "Bhoot",
    "version": "1.1.2"
}


### delete deployment
DELETE  {{baseURL}}deployment
Content-Type: application/json

{
    "templateName": "Rahman"
}